//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArchiveProject2019.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class main_lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal main_lang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ArchiveProject2019.Resources.main_lang", typeof(main_lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نشط؟.
        /// </summary>
        public static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عنوان الوثيقة.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عنوان الشركة.
        /// </summary>
        public static string CompanyAddress {
            get {
                return ResourceManager.GetString("CompanyAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ الشركة.
        /// </summary>
        public static string CompanyDate {
            get {
                return ResourceManager.GetString("CompanyDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نبذة عن الشركة.
        /// </summary>
        public static string CompanyDescription {
            get {
                return ResourceManager.GetString("CompanyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إسم الشركة.
        /// </summary>
        public static string CompanyName {
            get {
                return ResourceManager.GetString("CompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تأكيد كلمة المرور.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كلمة السر و كلمة التأكيد غير متوافقتين.
        /// </summary>
        public static string ConfirmPasswordCompare {
            get {
                return ResourceManager.GetString("ConfirmPasswordCompare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ الإنشاء.
        /// </summary>
        public static string CreatedAt {
            get {
                return ResourceManager.GetString("CreatedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أُنشئ بواسطة.
        /// </summary>
        public static string CreatedById {
            get {
                return ResourceManager.GetString("CreatedById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to القسم.
        /// </summary>
        public static string DepartmentId {
            get {
                return ResourceManager.GetString("DepartmentId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إسم القسم.
        /// </summary>
        public static string DepartmentName {
            get {
                return ResourceManager.GetString("DepartmentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب إدخال إسم القسم.
        /// </summary>
        public static string DepartmentNameRequired {
            get {
                return ResourceManager.GetString("DepartmentNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب إختيار القسم.
        /// </summary>
        public static string DepartmentRequired {
            get {
                return ResourceManager.GetString("DepartmentRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الوصف.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إسم الوثيقة.
        /// </summary>
        public static string DocName {
            get {
                return ResourceManager.GetString("DocName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حالة الوثيقة.
        /// </summary>
        public static string DocStatus {
            get {
                return ResourceManager.GetString("DocStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إسم الوثيقة.
        /// </summary>
        public static string Document_id {
            get {
                return ResourceManager.GetString("Document_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ اصدار الوثيقة.
        /// </summary>
        public static string DocumentDate {
            get {
                return ResourceManager.GetString("DocumentDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الوثيقة.
        /// </summary>
        public static string DocumentId {
            get {
                return ResourceManager.GetString("DocumentId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم الوثيقة.
        /// </summary>
        public static string DocumentNumber {
            get {
                return ResourceManager.GetString("DocumentNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب إختيار رقم الوثيقة.
        /// </summary>
        public static string DocumentNumberRequired {
            get {
                return ResourceManager.GetString("DocumentNumberRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب إختيار الوثيقة.
        /// </summary>
        public static string DocumentRequired {
            get {
                return ResourceManager.GetString("DocumentRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to البريد الإلكتروني.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صيغة البريد غير صحيحة.
        /// </summary>
        public static string EmailRequired {
            get {
                return ResourceManager.GetString("EmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إمكانية التعديل.
        /// </summary>
        public static string EnableEdit {
            get {
                return ResourceManager.GetString("EnableEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إمكانية الربط.
        /// </summary>
        public static string EnableRelate {
            get {
                return ResourceManager.GetString("EnableRelate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إمكانية الرد.
        /// </summary>
        public static string EnableReplay {
            get {
                return ResourceManager.GetString("EnableReplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إمكانية التسديد.
        /// </summary>
        public static string EnableSeal {
            get {
                return ResourceManager.GetString("EnableSeal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وضع العائلة.
        /// </summary>
        public static string FamelyState {
            get {
                return ResourceManager.GetString("FamelyState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم الحقل.
        /// </summary>
        public static string FieldId {
            get {
                return ResourceManager.GetString("FieldId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إسم الحقل.
        /// </summary>
        public static string FieldName {
            get {
                return ResourceManager.GetString("FieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب إدخال إسم الحقل.
        /// </summary>
        public static string FieldNameRequired {
            get {
                return ResourceManager.GetString("FieldNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قيمة الحقل.
        /// </summary>
        public static string FieldValue {
            get {
                return ResourceManager.GetString("FieldValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الملف.
        /// </summary>
        public static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إسم الملف.
        /// </summary>
        public static string FileName {
            get {
                return ResourceManager.GetString("FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الملف.
        /// </summary>
        public static string FileUrl {
            get {
                return ResourceManager.GetString("FileUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to النموذج.
        /// </summary>
        public static string FormId {
            get {
                return ResourceManager.GetString("FormId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إسم النموذج.
        /// </summary>
        public static string FormName {
            get {
                return ResourceManager.GetString("FormName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب إدخال اسم النموذج.
        /// </summary>
        public static string FormNameRequired {
            get {
                return ResourceManager.GetString("FormNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب إختيار النموذج.
        /// </summary>
        public static string FormRequired {
            get {
                return ResourceManager.GetString("FormRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الإسم الثلاثي.
        /// </summary>
        public static string FullName {
            get {
                return ResourceManager.GetString("FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب إدخال الإسم الثلاثي.
        /// </summary>
        public static string FullNameRequired {
            get {
                return ResourceManager.GetString("FullNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الجنس.
        /// </summary>
        public static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب إختيار الجنس.
        /// </summary>
        public static string GenderRequired {
            get {
                return ResourceManager.GetString("GenderRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المجموعة.
        /// </summary>
        public static string GroupId {
            get {
                return ResourceManager.GetString("GroupId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إسم المجموعة.
        /// </summary>
        public static string GroupName {
            get {
                return ResourceManager.GetString("GroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب إدخال إسم المجموعة.
        /// </summary>
        public static string GroupNameRequired {
            get {
                return ResourceManager.GetString("GroupNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نشط؟.
        /// </summary>
        public static string Is_Active {
            get {
                return ResourceManager.GetString("Is_Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ضروري؟.
        /// </summary>
        public static string IsRequired {
            get {
                return ResourceManager.GetString("IsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الإسم الوظيفي.
        /// </summary>
        public static string JobName {
            get {
                return ResourceManager.GetString("JobName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب إدخال الإسم الوظيفي.
        /// </summary>
        public static string JobNameRequired {
            get {
                return ResourceManager.GetString("JobNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الدور الوظيفي.
        /// </summary>
        public static string JobTitleId {
            get {
                return ResourceManager.GetString("JobTitleId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  يجب إدخال الإسم الوظيفي.
        /// </summary>
        public static string JobTitleRequired {
            get {
                return ResourceManager.GetString("JobTitleRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع الوثيقة.
        /// </summary>
        public static string KindId {
            get {
                return ResourceManager.GetString("KindId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع الوثيقة.
        /// </summary>
        public static string KindName {
            get {
                return ResourceManager.GetString("KindName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب إدخال نوع الوثيقة.
        /// </summary>
        public static string KindNameRequired {
            get {
                return ResourceManager.GetString("KindNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب إختيار النوع.
        /// </summary>
        public static string KindRequired {
            get {
                return ResourceManager.GetString("KindRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الشعار.
        /// </summary>
        public static string Logo {
            get {
                return ResourceManager.GetString("Logo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ البريد.
        /// </summary>
        public static string MailingDate {
            get {
                return ResourceManager.GetString("MailingDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم البريد.
        /// </summary>
        public static string MailingNumber {
            get {
                return ResourceManager.GetString("MailingNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عدد الاعضاء الاعظمي.
        /// </summary>
        public static string MaximumMember {
            get {
                return ResourceManager.GetString("MaximumMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب أن يكون العدد الأعظمي مقبول.
        /// </summary>
        public static string MaximumMemberRange {
            get {
                return ResourceManager.GetString("MaximumMemberRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب إدخال العدد الأعظمي.
        /// </summary>
        public static string MaximumMemberRequired {
            get {
                return ResourceManager.GetString("MaximumMemberRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to النص.
        /// </summary>
        public static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to موبايل أول.
        /// </summary>
        public static string MobileNumber1 {
            get {
                return ResourceManager.GetString("MobileNumber1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to موبايل ثان.
        /// </summary>
        public static string MobileNumber2 {
            get {
                return ResourceManager.GetString("MobileNumber2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاسم.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب أن يكون طول إسم النموذج اكبر محرفين وأصغر من 50.
        /// </summary>
        public static string NameLength {
            get {
                return ResourceManager.GetString("NameLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كلمة المرور الجديدة.
        /// </summary>
        public static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب إدخال كلمة المرور الجديدة.
        /// </summary>
        public static string NewPasswordRequired {
            get {
                return ResourceManager.GetString("NewPasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إسم المستخدم الجديد.
        /// </summary>
        public static string NewUserName {
            get {
                return ResourceManager.GetString("NewUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب إدخال إسم المستخدم الجديد.
        /// </summary>
        public static string NewUserNameRequired {
            get {
                return ResourceManager.GetString("NewUserNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ملاحظات.
        /// </summary>
        public static string Notes {
            get {
                return ResourceManager.GetString("Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريه التنبيه.
        /// </summary>
        public static string NotificationDate {
            get {
                return ResourceManager.GetString("NotificationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كلمة المرور الحالية.
        /// </summary>
        public static string OldPassword {
            get {
                return ResourceManager.GetString("OldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب إدخال كلمة المرور القديمة.
        /// </summary>
        public static string OldPasswordRequired {
            get {
                return ResourceManager.GetString("OldPasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إسم المستخدم الحالي.
        /// </summary>
        public static string OldUserName {
            get {
                return ResourceManager.GetString("OldUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كلمة المرور القديمة مطلوبة.
        /// </summary>
        public static string OldUserNameRequired {
            get {
                return ResourceManager.GetString("OldUserNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الجهة.
        /// </summary>
        public static string PartyId {
            get {
                return ResourceManager.GetString("PartyId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إسم الجهة.
        /// </summary>
        public static string PartyName {
            get {
                return ResourceManager.GetString("PartyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب إدخال إسم الجهة.
        /// </summary>
        public static string PartyNameRequired {
            get {
                return ResourceManager.GetString("PartyNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب إختيار الجهة.
        /// </summary>
        public static string PartyRequired {
            get {
                return ResourceManager.GetString("PartyRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كلمة المرور.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب أن يكون طول إسم النموذج اكبر محرفين وأصغر من 50.
        /// </summary>
        public static string PasswordLength {
            get {
                return ResourceManager.GetString("PasswordLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب إدخال كلمة المرور.
        /// </summary>
        public static string PasswordRequired {
            get {
                return ResourceManager.GetString("PasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إسم الصلاحية.
        /// </summary>
        public static string PermissionId {
            get {
                return ResourceManager.GetString("PermissionId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الصلاحية.
        /// </summary>
        public static string PermissionName {
            get {
                return ResourceManager.GetString("PermissionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم أرضي اول.
        /// </summary>
        public static string PhoneNumber1 {
            get {
                return ResourceManager.GetString("PhoneNumber1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم أرضي ثان.
        /// </summary>
        public static string PhoneNumber2 {
            get {
                return ResourceManager.GetString("PhoneNumber2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تذكرني؟.
        /// </summary>
        public static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المستخدم المسؤول.
        /// </summary>
        public static string ResponsibleUserId {
            get {
                return ResourceManager.GetString("ResponsibleUserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الدور.
        /// </summary>
        public static string Role {
            get {
                return ResourceManager.GetString("Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الدور.
        /// </summary>
        public static string RoleId {
            get {
                return ResourceManager.GetString("RoleId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إسم الدور.
        /// </summary>
        public static string RoleName {
            get {
                return ResourceManager.GetString("RoleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب إختيار إسم الدور.
        /// </summary>
        public static string RoleNameRequired {
            get {
                return ResourceManager.GetString("RoleNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب إختيار الدور.
        /// </summary>
        public static string RoleRequired {
            get {
                return ResourceManager.GetString("RoleRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إسم الوثيقة.
        /// </summary>
        public static string SealId {
            get {
                return ResourceManager.GetString("SealId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حالة الوثيقة.
        /// </summary>
        public static string StatusId {
            get {
                return ResourceManager.GetString("StatusId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الحالة.
        /// </summary>
        public static string StatusName {
            get {
                return ResourceManager.GetString("StatusName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إسم الحالة.
        /// </summary>
        public static string StatusNameRequired {
            get {
                return ResourceManager.GetString("StatusNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب إختيار الحالة.
        /// </summary>
        public static string StatusRequired {
            get {
                return ResourceManager.GetString("StatusRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الموضوع.
        /// </summary>
        public static string Subject {
            get {
                return ResourceManager.GetString("Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب إختيار الموضوع.
        /// </summary>
        public static string SubjectRequired {
            get {
                return ResourceManager.GetString("SubjectRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرمز الوظيفي.
        /// </summary>
        public static string Symbol {
            get {
                return ResourceManager.GetString("Symbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to النمط.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع البريد.
        /// </summary>
        public static string TypeMailId {
            get {
                return ResourceManager.GetString("TypeMailId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع البريد.
        /// </summary>
        public static string TypeMailName {
            get {
                return ResourceManager.GetString("TypeMailName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب إدخال إسم البريد.
        /// </summary>
        public static string TypeMailNameRequired {
            get {
                return ResourceManager.GetString("TypeMailNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب إختيار نمط البريد.
        /// </summary>
        public static string TypeMailRequired {
            get {
                return ResourceManager.GetString("TypeMailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نمط إظهار الوثائق.
        /// </summary>
        public static string TypeOfDisplayDocument {
            get {
                return ResourceManager.GetString("TypeOfDisplayDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب إختيار نمط إظهار الوثائق.
        /// </summary>
        public static string TypeOfDisplayDocumentRequired {
            get {
                return ResourceManager.GetString("TypeOfDisplayDocumentRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نمط إظهار النماذج.
        /// </summary>
        public static string TypeOfDisplayForm {
            get {
                return ResourceManager.GetString("TypeOfDisplayForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب إختيار نمط إظهار النماذج.
        /// </summary>
        public static string TypeOfDisplayFormRequired {
            get {
                return ResourceManager.GetString("TypeOfDisplayFormRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ تعديل.
        /// </summary>
        public static string UpdatedAt {
            get {
                return ResourceManager.GetString("UpdatedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عُدل بواسطة.
        /// </summary>
        public static string UpdatedById {
            get {
                return ResourceManager.GetString("UpdatedById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إسم المستخدم.
        /// </summary>
        public static string UserId {
            get {
                return ResourceManager.GetString("UserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إسم المستخدم.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب إدخال إسم المستخدم.
        /// </summary>
        public static string UserNameRequired {
            get {
                return ResourceManager.GetString("UserNameRequired", resourceCulture);
            }
        }
    }
}
