// <auto-generated />
namespace ArchiveProject2019.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class companyUpdate3 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(companyUpdate3));
        
        string IMigrationMetadata.Id
        {
            get { return "201911241757045_companyUpdate3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
